Repository FRONTENDSCHOOLPLUS2/HighlighTalk, pull requests merged in 2024-08, with the labels that each got.

#13 [Docs] gitignore에 env 추가 및 Readme 파일 베이스 작성 #11
  .gitignore
  README.md
Labels: 📚 Docs, ⚙️ Chore

#14 [Chore/Feat] husky Git Hook을 적용하여 커밋명 검사를 시행한다.
  .eslintrc.json
  .husky/commit-msg
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Chore, ✨ Feature

#15 [Feat] gpt api 연동 및 구현 가능성 테스트
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/(home)/home.scss
  src/app/(home)/page.tsx
  src/app/api/generate/route.js
  src/components/CsvFileUploader.tsx
  tsconfig.json
Labels: ✨ Feature

#18 [Feat] gpt 프롬프팅 구현 세분화, 파일업로드 기능 구현, 멀티 스텝 기능 구현
  pnpm-lock.yaml
  src/app/(home)/page.tsx
  src/app/api/generate/route.js
  src/app/upload/page.tsx
  src/components/CsvFileUploader.tsx
  src/components/FileUpload/FileUploader.scss
  src/components/FileUpload/FileUploader.tsx
  src/components/fetchData.ts
Labels: ✨ Feature, 🌟 Prompting

#22 [Feat] 파일업로드 함수 분리 반응형 레이아웃 구현
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/(home)/home.scss
  src/app/(home)/page.tsx
  src/app/freetest/TestPage.scss
  src/app/freetest/page.tsx
  src/app/layout.tsx
  src/components/File/FileHandler.tsx
  src/components/FileUpload/FileUploader.scss
  src/components/FileUpload/FileUploader.tsx
  src/components/layout/Header.tsx
  src/components/layout/Header/Header.scss
  src/components/layout/Header/Header.tsx
  src/hooks/fetchData.ts
  src/styles/common.css
  src/styles/responsible.css
  src/styles/variable.css
Labels: ✨ Feature, 🎨 UI, 🌟 Prompting

#28 [Test] gpt-tokenizer 라이브러리 테스트 코드 작성
  package.json
  pnpm-lock.yaml
  src/app/test/page.tsx
  src/components/test/TokenTest.tsx
  src/utils/getTokenLength.ts
Labels: ✨ Feature, 🌟 Prompting

#35 [Design] 로그인, 회원가입 페이지의 UI를 구현한다.
  src/app/(user)/login/.gitkeep
  src/app/(user)/login/_LoginPage.scss
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/.gitkeep
  src/app/(user)/signup/_SignupPage.scss
  src/app/(user)/signup/page.tsx
  src/styles/reset.css
Labels: 💡 Follow-up, 🎨 UI

#42 [Feat] upload 컴포넌트 분리 및 UI 작업 #41
  public/image/icon_blue_s.svg
  public/image/icon_yellow_s.svg
  src/app/freetest/_TestPage.scss
  src/components/FileUpload/Description/DescriptionArea.tsx
  src/components/FileUpload/FileUploader.tsx
  src/components/FileUpload/UploadArea/UploadArea.tsx
  src/components/FileUpload/UploadArea/_UploadArea.scss
  src/components/FileUpload/_FileUploader.scss
  src/components/UploadArea/UploadArea.tsx
  src/components/layout/Header/Header.scss
  src/hooks/fetchData.ts
  src/styles/variable.css
  src/utils/removeDateTimeAndUserKey.ts
Labels: ✨ Feature, 🎨 UI

#48 Fix: validateAndTrimData 함수에서 data trim 시 최근 데이터 기준으로 자르기 #46
  src/utils/validateAndTrimData.ts
Labels: ✨ Feature

#56 [Feat] 메인페이지추가 , 파일명 변경 , 공용 모달 컴포넌트 생성
  pnpm-lock.yaml
  public/image/coin.svg
  src/app/(home)/_home.scss
  src/app/(home)/page.tsx
  src/app/api/generate/route.ts
  src/components/Button/Button.tsx
  src/components/FileUpload/FileUploader.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/_Modal.scss
  src/hooks/useGpt.ts
Labels: ⚙️ Chore, ✨ Feature, 🎨 UI

#59 [Fix] Button타입 수정 및 props 이름 변경 #45
  src/app/test/page.tsx
  src/components/Button/Button.tsx
  src/components/Button/_Button.scss
Labels: 🐛 Bug, ✨ Feature

#61 [Feat] gpt 테마 고도화 버튼사용부분 일부 변경
  src/app/(home)/page.tsx
  src/app/(tests)/freetest/page.tsx
  src/app/(tests)/lovetest/page.tsx
  src/components/FileUpload/FileUploader.tsx
  src/components/FileUpload/UploadArea/UploadArea.tsx
  src/components/Modal/Modal.tsx
Labels: ♻️ Refactor, 🌟 Prompting

#64 [Feat] 결과 페이지 분리를 위한 작업 입니다.
  backend_API/01.회원/회원 정보 조회(모든 속성).bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 등록.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  backend_API/environments/dev.bru
  src/app/(home)/page.tsx
  src/app/(tests)/freetest/[id]/page.tsx
  src/app/(tests)/lovetest/[id]/page.tsx
  src/app/api/generate/route.ts
  src/components/FileUpload/FileUploader.tsx
  src/components/FileUpload/page.tsx
  src/components/Modal/Modal.tsx
  src/store/ModalStore.ts
Labels: ✨ Feature, 🌟 Prompting

#74 [Feat] 메인페이지 컴포넌트 분리 및 ui 구현 ,메타데이터 파비콘 추가
  .gitignore
  package.json
  pnpm-lock.yaml
  public/image/character_4.svg
  public/image/character_5.svg
  public/image/coin.svg
  public/image/main-slide-bg.svg
  public/image/mainslide1.svg
  public/image/mainslide2.svg
  public/image/mbti/default.svg
  public/image/mbti/enfj.svg
  public/image/mbti/enfp.svg
  public/image/mbti/entj.svg
  public/image/mbti/entp.svg
  public/image/mbti/esfj.svg
  public/image/mbti/esfp.svg
  public/image/mbti/estj.svg
  public/image/mbti/estp.svg
  public/image/mbti/infj.svg
  public/image/mbti/infp.svg
  public/image/mbti/intj.svg
  public/image/mbti/intp.svg
  public/image/mbti/isfj.svg
  public/image/mbti/isfp.svg
  public/image/mbti/istj.svg
  public/image/mbti/istp.svg
  public/image/notice-icon/notice1.svg
  public/image/notice-icon/notice2.svg
  public/image/notice-icon/notice3.svg
  public/image/notice-icon/notice4.svg
  src/app/(home)/_home.scss
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/components/FileUpload/UploadArea/_UploadArea.scss
  src/components/FileUpload/_FileUploader.scss
  src/components/MainItems/MainItems.tsx
  src/components/MainNotice/MainNotice.tsx
  src/components/MainSlide/MainSlide.tsx
  src/components/MainThemeItems/MainThemeItems.tsx
  src/components/MainThemeItems/MainThemes.tsx
  src/components/Mbti/Mbti.tsx
  src/components/Mbti/_Mbti.scss
  src/utils/getImageSrc.ts
Labels: ✨ Feature, 🎨 UI, 🌟 Prompting

#79 [Feat] 메인페이지디테일 수정 #75-1
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  public/image/character_3_left.svg
  public/image/mainslide1.svg
  public/image/mainslide2.svg
  src/app/(home)/_home.scss
  src/components/MainItems/MainItems.tsx
  src/components/MainNotice/MainNotice.tsx
  src/components/MainThemeItems/MainThemeItems.tsx
  src/components/MainThemeItems/MainThemes.tsx
  src/styles/responsible.css
Labels: 🎨 UI

#91 [Feat] 게시판 기능 구현 서버액션 함수 생성
  backend_API/01.회원/회원 정보 조회(모든 속성).bru
  backend_API/05.게시판(QnA, 공지 등)/01.목록 조회/게시물 목록 조회(댓글순 정렬).bru
  backend_API/05.게시판(QnA, 공지 등)/02.댓글/댓글 등록.bru
  backend_API/05.게시판(QnA, 공지 등)/02.댓글/댓글 목록 조회.bru
  backend_API/05.게시판(QnA, 공지 등)/02.댓글/댓글 삭제.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 등록(태그 추가).bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 등록.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 삭제.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 수정.bru
  public/image/character_1.svg
  src/app/api/generate/route.ts
  src/app/posts/PostListItem.tsx
  src/app/posts/[id]/CommentItem.tsx
  src/app/posts/[id]/CommentList.tsx
  src/app/posts/[id]/CommentNew.tsx
  src/app/posts/[id]/PostInfo.tsx
  src/app/posts/[id]/_detail.scss
  src/app/posts/[id]/edit/page.tsx
  src/app/posts/[id]/page.tsx
  src/app/posts/_post.scss
  src/app/posts/new/_newPosts.scss
  src/app/posts/new/newPosts.tsx
  src/app/posts/new/page.tsx
  src/app/posts/notice/NoticeItem.tsx
  src/app/posts/notice/page.tsx
  src/app/posts/page.tsx
  src/auth.ts
  src/components/Button/Button.tsx
  src/components/FileUpload/FileUploader.tsx
  src/serverActions/fetchServerAction/deletePostItem.ts
  src/serverActions/fetchServerAction/deleteReplies.ts
  src/serverActions/fetchServerAction/getAllReplies.ts
  src/serverActions/fetchServerAction/getDataFetch.ts
  src/serverActions/fetchServerAction/getNoticeData.ts
  src/serverActions/fetchServerAction/sendComment.ts
  src/serverActions/fetchServerAction/sendPostData.ts
  src/types/posts.ts
Labels: ✨ Feature, 🎨 UI

#93 [Feat] 분석 결과 페이지 UI 구현 및 조회 기능 구현 #84
  public/image/more_horizontal.svg
  src/app/(user)/mypage/archive/_ArchivePage.scss
  src/app/(user)/mypage/archive/components/Card/Card.tsx
  src/app/(user)/mypage/archive/components/Card/_Card.scss
  src/app/(user)/mypage/archive/components/CategoryList/CategoryList.tsx
  src/app/(user)/mypage/archive/components/CategoryList/_CategoryList.scss
  src/app/(user)/mypage/archive/components/Menu/Menu.tsx
  src/app/(user)/mypage/archive/components/Menu/_Menu.scss
  src/app/(user)/mypage/archive/components/NoDataNotification/NoDataNotification.tsx
  src/app/(user)/mypage/archive/components/NoDataNotification/_NoDataNotification.scss
  src/app/(user)/mypage/archive/page.tsx
  src/app/api/generate/route.ts
  src/components/Button/_Button.scss
Labels: ✨ Feature

#94 Fix: 내 결과 보관함 조회 안되는 오류 해결 #84
  src/app/(user)/mypage/archive/components/Card/Card.tsx
  src/app/(user)/mypage/archive/page.tsx
Labels: ✨ Feature

#100 [Fix] 오류를 유발하는 코드 및 페이지 삭제, 타입 수정 +wordCloud 리사이징 구현 #97
  src/app/(tests)/freetest/[id]/components/PopularWordSection/PopularWordSection.tsx
  src/app/(tests)/freetest/[id]/page.tsx
  src/app/(tests)/lovetest/[id]/page.tsx
  src/app/(user)/mypage/archive/page.tsx
  src/app/posts/page.tsx
  src/app/test/page.tsx
  src/components/graph/CirclePacking.tsx
  src/components/graph/WordCloud.tsx
  src/store/useUserStore.ts
Labels: ✨ Feature, 🗃 Infra

#105 [Feat] 메인페이지 레이아웃 수정 , css변수 수정 ,lovetest버그수정#99
  .gitignore
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  src/app/(home)/_home.scss
  src/app/(home)/page.tsx
  src/app/api/generate/route.ts
  src/app/error.tsx
  src/app/posts/Pagination.tsx
  src/app/posts/_post.scss
  src/app/posts/new/page.tsx
  src/app/posts/notice/page.tsx
  src/components/FileUpload/Description/DescriptionArea.tsx
  src/components/FileUpload/FileUploader.tsx
  src/components/FileUpload/UploadArea/UploadArea.tsx
  src/components/FileUpload/UploadArea/_UploadArea.scss
  src/components/MainSlide/MainSlide.tsx
  src/components/MainThemeItems/MainThemeItems.tsx
  src/styles/responsible.css
  src/styles/variable.css
Labels: ✨ Feature, 🎨 UI, 🌟 Prompting

#108 [Fix] ProtectedRoute 병합 충돌 이전 버전으로 적용되었던 문제 해결 #107
  src/components/ProtectedRoute/ProtectedRoute.tsx
Labels: 🚑 Hotfix

#110 [Fix] 결과 보관함 데이터 Fetching 오류 수정 및 데이터타입 지정 #85
  src/app/(user)/mypage/archive/components/Card/Card.tsx
  src/app/(user)/mypage/archive/components/CategoryList/CategoryList.tsx
  src/app/(user)/mypage/archive/page.tsx
  src/data/freetest.json
  src/data/lovetest.json
  src/serverActions/archiveAction.ts
  src/types/index.ts
  src/types/posts.ts
  src/types/test.ts
Labels: 🐛 Bug, ✨ Feature

#111 [Feat] 반응형 작업 , 인트로 페이지 서버컴포넌트로 분리#106
  .gitignore
  backend_API/01.회원/01.로그인/일반 회원 로그인(_id=4).bru
  backend_API/01.회원/회원 정보 조회(북마크 목록).bru
  backend_API/02.일반 회원/02.구매/구매 상세 조회.bru
  backend_API/02.일반 회원/02.구매/상품 구매.bru
  backend_API/02.일반 회원/02.구매/주문 상태 수정(반품 요청, 주문별).bru
  backend_API/05.게시판(QnA, 공지 등)/01.목록 조회/게시물 목록 조회(검색, 상품 id).bru
  backend_API/05.게시판(QnA, 공지 등)/01.목록 조회/내가 작성한 게시물 목록 조회(QnA).bru
  backend_API/05.게시판(QnA, 공지 등)/01.목록 조회/지정한 사용자가 작성한 게시물 목록 조회(QnA).bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 등록.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 삭제.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  public/image/character_8.png
  public/image/notice-icon/notice3.svg
  src/app/(home)/_home.scss
  src/app/(home)/page.tsx
  src/app/(tests)/freetest/FreeTestContainer.tsx
  src/app/(tests)/freetest/_TestPage.scss
  src/app/(tests)/freetest/page.tsx
  src/app/(tests)/lovetest/ LoveTestContainer.tsx
  src/app/(tests)/lovetest/page.tsx
  src/app/(user)/mypage/MyPageProfile.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/app/posts/[id]/page.tsx
  src/app/posts/_post.scss
  src/app/posts/page.tsx
  src/components/ MainCommPreviews/MainCommPreview.tsx
  src/components/ MainCommPreviews/MainCommPreviewItem.tsx
  src/components/ MainCommPreviews/_mainCommPreview.scss
  src/components/FileUpload/FileUploader.tsx
  src/components/MainItems/MainItems.tsx
  src/components/MainNotice/MainNotice.tsx
  src/components/MainNotice/MainSeverNotice.tsx
  src/components/MainNotice/_mainSeverNotice.scss
  src/components/MainThemeItems/MainThemeItems.tsx
  src/components/MainThemeItems/MainThemes.tsx
  src/data/lovetest.json
  src/serverActions/fetchServerAction/getDataFetch.ts
  src/serverActions/fetchServerAction/getNoticeData.ts
  src/serverActions/fetchServerAction/sendPostData.ts
  src/styles/error.scss
  src/styles/not-found.css
  src/styles/not-found.scss
Labels: ✨ Feature, 🎨 UI

#115 [Feat] 최적화 및 config 파일 수정 , 인트로 페이지 작업 등 진행
  .gitignore
  backend_API/05.게시판(QnA, 공지 등)/게시물 등록.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 삭제.bru
  backend_API/05.게시판(QnA, 공지 등)/게시물 상세 조회.bru
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/image/icon_chat.svg
  public/image/icon_eye.svg
  public/image/icon_pen.svg
  public/image/intro_bg1.svg
  public/image/intro_bg2.png
  public/image/intro_card1.svg
  src/app/(home)/_home.scss
  src/app/(tests)/freetest/FreeTestContainer.tsx
  src/app/(tests)/freetest/[id]/components/MbtiSection/MbtiSection.tsx
  src/app/(tests)/freetest/[id]/components/MbtiSection/_MbtiSection.scss
  src/app/(tests)/freetest/_FreeTestPage.scss
  src/app/(tests)/freetest/_TestPage.scss
  src/app/(tests)/freetest/page.tsx
  src/app/(tests)/lovetest/ LoveTestContainer.tsx
  src/app/(tests)/lovetest/LoveTestContainer.tsx
  src/app/(tests)/lovetest/_loveTestPage.scss
  src/app/(tests)/lovetest/page.tsx
  src/app/api/generate/route.ts
  src/app/posts/Pagination.tsx
  src/app/posts/_post.scss
  src/components/ MainCommPreviews/MainCommPreview.tsx
  src/components/ MainCommPreviews/MainCommPreviewItem.tsx
  src/components/ MainCommPreviews/_mainCommPreview.scss
  src/components/FileUpload/UploadArea/_UploadArea.scss
  src/components/FileUpload/page.tsx
  src/components/MainItems/MainItems.tsx
  src/components/MainNotice/MainNotice.tsx
  src/components/MainSlide/MainSlide.tsx
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/_Spinner.scss
  src/components/test/TokenTest.tsx
  src/hooks/useGpt.ts
  src/serverActions/fetchServerAction/deleteReplies.ts
  src/serverActions/fetchServerAction/getDataFetch.ts
Labels: ⚙️ Chore, ✨ Feature, 🎨 UI

#136 [Feat] 파일 업로드 부분 수정 이미지 추가 #133
  public/image/pc_image.png
  src/components/FileUpload/Description/DescriptionArea.tsx
  src/components/FileUpload/UploadArea/_UploadArea.scss
  src/components/MainItems/MainItems.tsx
Labels: ✨ Feature, 🎨 UI

#138 [HotFix] createOrder 타입 에러 해결 string -> OrderInfoType #137
  src/hooks/useOrderAction.ts
Labels: 🚑 Hotfix

#140 [HotFix] 연애 결과 페이지 데이터 구조 수정 #139
  src/app/(tests)/lovetest/[id]/page.tsx
  src/data/lovetest.json
  src/types/test.ts
Labels: 🐛 Bug

#141 [Docs] 프로젝트 README.md를 작성한다.
  README.md
Labels: 📚 Docs

#144 [Docs] 리드미 파일 수정
  README.md
Labels: 📚 Docs

#152 [Refactor] 파일 확장자 기능 추가
  README.md
  src/components/FileUpload/FileUploader.tsx
  src/components/FileUpload/UploadArea/UploadArea.tsx
Labels: ♻️ Refactor
